kind: Service
apiVersion: v1
metadata:
  name: react-k8s-info
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: react-k8s-info